# Generated by Django 5.1.6 on 2025-02-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
